[default]
ENV="development"
DB_API="postgresql+psycopg2"
BUCKET_EXERCISES="sharpener-exercises"
BUCKET_SUBMISSIONS="sharpener-submissions"
DB_NAME="postgres"
DB_USERNAME=""
DB_PASSWORD=""
DB_CONN_NAME=""
GITHUB_URI_OAUTH=""
GITHUB_URI_USER=""
GITHUB_CLIENT_ID=""
GITHUB_CLIENT_SECRET=""
FLASK_SECRET=""
