name: Deploying to GCloud App Engine 
on:
  push:
    branches: 
    - "master"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1.1.0
        with:
          args: --recursive --in-place --aggressive --aggressive .
      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1  

  deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: Setup Google Cloud auth
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - uses: actions/checkout@master
    - name: Setting up environment variables
      env:
        DYNACONF_ENV: production
        DYNACONF_DB_USERNAME: ${{ secrets.db_username }}
        DYNACONF_DB_PASSWORD: ${{ secrets.db_password }}
        DYNACONF_DB_API: ${{ secrets.db_api }}
        DYNACONF_DB_NAME: ${{ secrets.db_name }}
        DYNACONF_DB_CONN_NAME: ${{ secrets.db_conn_name }}
        DYNACONF_GITHUB_CLIENT_SECRET: ${{ client_secret }}
        DYNACONF_GITHUB_CLIENT_ID: ${{ client_id }
        DYNACONF_GITHUB_URI_USER: "https://github.com/login/oauth/access_token"
        DYNACONF_GITHUB_URI_OAUTH: "https://api.github.com/user"
      run: env | grep DYNACONF_ > .env
    - name: Deploy to GCP AppEngine
      uses: actions/gcloud/cli@master
      with:
        args: "app deploy --project $PROJECT_ID app.yaml"
      env:
        PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
