name: Linting and Testing
on: 
  push:
    branches:
      - '**'
      - '!master'
    pull_request:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1.1.0
        with:
          args: --recursive --in-place --aggressive --aggressive .
      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1
